---
name: Integration tests on Azure
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  integration-tests-azure:
    name: Regular
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        profile: ["ci_azure_auto"]
        msodbc_version: ["17", "18"]
      max-parallel: 1
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:CI-${{ matrix.python_version }}-msodbc${{ matrix.msodbc_version }}
    steps:
      - name: AZ CLI login
        run: az login --service-principal --username="${AZURE_CLIENT_ID}" --password="${AZURE_CLIENT_SECRET}" --tenant="${AZURE_TENANT_ID}"
        env:
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      - name: Run functional tests
        env:
          DBT_AZURESQL_SERVER: ${{ secrets.DBT_AZURESQL_SERVER }}
          DBT_AZURESQL_DB: ${{ secrets.DBT_AZURESQL_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          FABRIC_TEST_DRIVER: 'ODBC Driver ${{ matrix.msodbc_version }} for SQL Server'
          DBT_TEST_USER_1: dbo
          DBT_TEST_USER_2: dbo
          DBT_TEST_USER_3: dbo
        run: pytest -ra -v tests/functional --profile "${{ matrix.profile }}"
