---
name: Integration tests on Fabric DW
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  integration-tests-fabric-dw:
    name: Regular
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python_version: ["3.12", "3.13"]
        msodbc_version: ["17", "18"]

    runs-on: ubuntu-latest
    permissions:
      contents: read   # Required to access repository files
      packages: read   # Grant explicit read access to packages
      id-token: write  # Needed if using OIDC authentication
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Run functional tests
        env:
          FABRIC_TEST_ENDPOINT: ${{ secrets.DBT_AZURESQL_SERVER }}
          FABRIC_TEST_DWH_NAME: ${{ secrets.DBT_AZURESQL_DB }}
        run: uv run pytest -ra -v tests/functional
