---
name: Integration tests on Fabric DW
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - oidc_connect

permissions:
  id-token: write
  contents: read

jobs:
  integration-tests-fabric-dw:
    name: Regular
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        profile: ["ci_azure_auto"]
        python_version: ["3.11"]
        msodbc_version: ["17", "18"]

    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        federated-token: ${{ secrets.GITHUB_TOKEN }}
        allow-no-subscriptions: true
