---
name: Publish Docker images for CI/CD
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - 'devops/**'
      - '.github/workflows/publish-docker.yml'
    branches:
      - main
      - v*

jobs:
  publish-docker-client:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        docker_target: ["msodbc17", "msodbc18"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: devops
          build-args: PYTHON_VERSION=${{ matrix.python_version }}
          file: devops/CI.Dockerfile
          push: true
          platforms: linux/amd64
          target: ${{ matrix.docker_target }}
          tags: ghcr.io/${{ github.repository }}:CI-${{ matrix.python_version }}-${{ matrix.docker_target }}

      - name: List Docker images
        run: docker images ghcr.io/${{ github.repository }}
