---
name: Publish Docker images for CI/CD
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/CI.Dockerfile'
      - '.github/workflows/publish-docker.yml'
    branches:
      - main
      - v*

jobs:
  publish-docker-client:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        docker_target: ["msodbc17", "msodbc18"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          build-args: PYTHON_VERSION=${{ matrix.python_version }}
          file: .github/CI.Dockerfile
          push: true
          target: ${{ matrix.docker_target }}
          tags: ghcr.io/${{ github.repository }}:CI-${{ matrix.python_version }}-${{ matrix.docker_target }}
          platforms: ${{ matrix.docker_target == 'msodbc17' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}