---
name: Release new version

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  release-version:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: '3.11'

      - name: Verify version match
        run: uv run scripts/verify_version.py "$GITHUB_REF_NAME"

      - name: Build and publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_DBT_FABRIC }}
        run: |
          rm -rf dist
          uv build
          uv publish
